version: '3.8'

services:
  colrates:
    build:
      context: .
      dockerfile: colrates/Dockerfile
    environment:
      - DJANGO_SUPERUSER_USERNAME=shtodav
      - DJANGO_SUPERUSER_PASSWORD=secret
      - DATABASE_USER=shtodav
      - DATABASE_PASSWORD=secret
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=colrates
    depends_on:
      - postgres
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=shtodav
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=colrates
  postgres-admin:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile
    ports:
    - 80:80
    environment:
      - RATES_HOST=colrates
      - RATES_PORT=8000
    depends_on:
      - colrates

volumes:
  postgres_data: