version: '3.8'

services:
  colrates:
    build: .
    ports:
      - 8000:8000
    environment:
      - DJANGO_SUPERUSER_USERNAME=shtodav
      - DJANGO_SUPERUSER_PASSWORD=secret
    depends_on:
      - postgres
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=shtodav
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=colrates
  postgres-admin:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  nginx:
    image: nginx
    ports:
    - 80:80
    volumes:
    - ./nginx/static:/usr/share/nginx/html/static:ro
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres_data: