version: '3.8'

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=shtodav
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=colrates
  colrates:
    build:
      context: .
      dockerfile: colrates/Dockerfile
    environment:
      - DJANGO_SUPERUSER_USERNAME=shtodav
      - DJANGO_SUPERUSER_PASSWORD=secret
      - DATABASE_USER=shtodav
      - DATABASE_PASSWORD=secret
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=colrates
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
  colrates-proxy:
    build:
      context: nginx/
      dockerfile: Dockerfile
    ports:
    - 80:80
    environment:
      - RATES_HOST=colrates
      - RATES_PORT=8000
    depends_on:
      - colrates
  ecb-poller:
    build:
      context: .
      dockerfile: ecb-poller/Dockerfile
    environment:
      - RATES_URL=http://colrates-proxy
    depends_on:
      - colrates-proxy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5

volumes:
  postgres_data: