# Generated by Django 3.1.1 on 2020-09-05 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0005_auto_20200905_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='base_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='base_currency', to='rates.currency'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='currency_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='rates.currency'),
        ),
    ]
