# Generated by Django 3.1.1 on 2020-09-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0007_auto_20200905_1220'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.UniqueConstraint(fields=('base_id', 'currency_id', 'date'), name='unique_rate'),
        ),
    ]
