# Generated by Django 3.1.1 on 2020-09-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0008_auto_20200905_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
