# Generated by Django 3.1.1 on 2020-09-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0009_auto_20200906_0847'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rate',
            name='unique_rate',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='base_id',
            new_name='base',
        ),
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.UniqueConstraint(fields=('base', 'currency_id', 'date'), name='unique_rate'),
        ),
    ]
