# Generated by Django 3.1.1 on 2020-09-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0010_auto_20200920_0838'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rate',
            name='unique_rate',
        ),
        migrations.RemoveIndex(
            model_name='rate',
            name='currency_index',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='currency_id',
            new_name='currency',
        ),
        migrations.AddIndex(
            model_name='rate',
            index=models.Index(fields=['currency'], name='currency_index'),
        ),
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.UniqueConstraint(fields=('base', 'currency', 'date'), name='unique_rate'),
        ),
    ]
