# Generated by Django 3.1.1 on 2020-09-05 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='rate_id',
            new_name='currency_id',
        ),
    ]
