# Generated by Django 3.1.1 on 2020-09-05 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0004_auto_20200905_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='currency_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.currency'),
        ),
    ]
