node('docker && python') {
    def proxy

    stage('Clone repository') {
        checkout scm
    }

    stage('Build image') {
        sh 'pip install -r requirements.txt'
        dir('colrates/src') {
            sh 'python3 manage.py collectstatic --noinput'
        }
        dir('nginx') {
            proxy = docker.build('davydstoppel/colrates-proxy')
        }
    }

    stage('Run container') {
        def container = 'colrates-proxy'
        try {
            sh "docker stop $container"
        } catch (err) {
        }
        try {
            sh "docker rm $container"
        } catch (err) {
        }
        proxy.run("--name $container --restart=always -e RATES_HOST=${params.RATES_HOST} -e RATES_PORT=${params.RATES_PORT}")
    }

    stage('Push image') {
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
            proxy.push('latest')
        }
    }
}