node('docker && python') {
    def proxy
    def colrates

    stage('Clone repository') {
        checkout scm
    }

    stage('Build colrates reverse proxy') {
        sh "python3 colrates/src/manage.py collectstatic --noinput"
        sh "pip install -r requirements.txt"
        proxy = docker.build("davydstoppel/colrates-proxy", "nginx")
    }

    stage('Build colrates image') {
        colrates = docker.build("davydstoppel/colrates", "-f colrates/Dockerfile .")
    }

    stage('Push colrates reverse proxy image') {
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
            proxy.push("latest")
        }
    }

    stage('Push colrates image') {
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
            colrates.push("latest")
        }
    }
}